# Generated by Django 4.2.17 on 2025-01-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=254)),
                ('country_code', models.CharField(max_length=3)),
                ('year', models.DateField()),
                ('scizophrenia', models.DecimalField(blank=True, decimal_places=6, max_digits=7)),
                ('bipolar_disorder', models.DecimalField(blank=True, decimal_places=6, max_digits=7)),
                ('eating_disorders', models.DecimalField(blank=True, decimal_places=6, max_digits=7)),
                ('anxiety_disorders', models.DecimalField(blank=True, decimal_places=6, max_digits=7)),
                ('depression', models.DecimalField(blank=True, decimal_places=6, max_digits=7)),
                ('drug_use_disorders', models.DecimalField(blank=True, decimal_places=6, max_digits=7)),
                ('alcohol_use_disorders', models.DecimalField(blank=True, decimal_places=6, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Mental Health',
            },
        ),
    ]
