# Generated by Django 4.2.17 on 2025-01-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalhealth',
            name='alcohol_use_disorders',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealth',
            name='anxiety_disorders',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealth',
            name='bipolar_disorder',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealth',
            name='country',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealth',
            name='country_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealth',
            name='depression',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealth',
            name='drug_use_disorders',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealth',
            name='eating_disorders',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealth',
            name='scizophrenia',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealth',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
