# Generated by Django 4.2.17 on 2025-01-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_mentalhealth_alcohol_use_disorders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalhealth',
            name='alcohol_use_disorders',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealth',
            name='anxiety_disorders',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealth',
            name='bipolar_disorder',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealth',
            name='depression',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealth',
            name='drug_use_disorders',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealth',
            name='eating_disorders',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealth',
            name='scizophrenia',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
    ]
