# Generated by Django 4.2.17 on 2025-01-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_remove_mentalhealth_alcohol_use_disorders_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentalhealth',
            old_name='scizophrenia',
            new_name='schizophrenia',
        ),
        migrations.RemoveField(
            model_name='mentalhealth',
            name='year',
        ),
        migrations.AddField(
            model_name='mentalhealth',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
