# Generated by Django 4.2.17 on 2025-01-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_rename_scizophrenia_mentalhealth_schizophrenia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentalhealth',
            old_name='schizophrenia',
            new_name='schitzophrenia',
        ),
    ]
